kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: armada-test
nodes:
- role: control-plane
  image: kindest/node:v1.21.10
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80 # port of the nginx ingress controller
    hostPort: 8500 # expose ingresses on localhost:5000
    protocol: TCP
  - containerPort: 3000 # arbitrary port used to test "node port services"
    hostPort: 8600 # expose service on localhost:3000
    protocol: TCP
- role: worker
  image: "kindest/node:v1.21.10"
