postgres:
  maxOpenConns: 5
  maxIdleConns: 25
  connMaxLifetime: 30m
  connection:
    host: localhost
    port: 5433
    user: postgres
    password: psw
    dbname: postgres
    sslmode: disable
metrics:
  port: 11001
pulsar:
  enabled: true
  URL: "pulsar://localhost:6650"
  jobsetEventsTopic: "persistent://armada/armada/events"
  receiveTimeout: "10s"
  backoffTime: "5s"
subscriptionName: "lookout-ingester-v2"
batchSize: 10000
batchDuration: 500ms
minJobSpecCompressionSize: 1024
userAnnotationPrefix: "armadaproject.io/"
maxAttempts: 10
maxBackoff: 60
