corsAllowedOrigins: ["http://localhost:3000", "http://localhost:8089"]
auth:
  basicAuth:
    enableAuthentication: false
  anonymousAuth: true
  permissionGroupMapping:
    submit_jobs: ["everyone"]
    submit_any_jobs: ["everyone"]
    create_queue: ["everyone"]
    delete_queue: ["everyone"]
    cancel_jobs: ["everyone"]
    cancel_any_jobs: ["everyone"]
    reprioritize_jobs: ["everyone"]
    reprioritize_any_jobs: ["everyone"]
    watch_events: ["everyone"]
    watch_all_events: ["everyone"]
    execute_jobs: ["everyone"]
    cordon_nodes: ["everyone"]
pulsar:
  enabled: false
eventapi:
  postgres:
    connection:
      host: "localhost"
redis:
  addrs:
    - localhost:6379
  password: ""
  db: 0
  poolSize: 1000
eventsApiRedis:
  addrs:
    - localhost:6379
  password: ""
  db: 1
  poolSize: 1000
